name: My Playwright Tests

on: [push, pull_request]

jobs:
  playwright-run:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up environment variables
        run: |
          echo "BASE_URL_STAGING=${{ secrets.BASE_URL_STAGING }}" >> $GITHUB_ENV
          echo "HTTP_USERNAME=${{ secrets.HTTP_USERNAME }}" >> $GITHUB_ENV
          echo "HTTP_PASSWORD=${{ secrets.HTTP_PASSWORD }}" >> $GITHUB_ENV
          echo "AUTH_URL=${{ secrets.AUTH_URL }}" >> $GITHUB_ENV
          echo "AUTH_FILE_PATH=${{ secrets.AUTH_FILE_PATH }}" >> $GITHUB_ENV
          echo "EMAIL=${{ secrets.EMAIL }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright test results
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: playwright-report
