name: Playwright API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: mcr.microsoft.com/playwright:v1.39.0-jammy
          options: -v /home/runner/work/playwright:/workspace

      - name: Install dependencies
        run: |
          cd /workspace
          npm install

      - name: Run Playwright API tests
        run: |
          cd /workspace
          npx playwright install
          npx playwright test tests/api-test.spec.js
